sentry:
  build: .
  restart: always
  links:
    - redis
    - postgres
  ports:
    - "80:9000"

# uncomment if you need automated backups to Amazon S3
#pgbackup:
#  image: ffedoroff/docker-postgres-s3-backup
#  restart: always
#  links:
#    - postgres
#  environment:
#    - SCHEDULE=* * * * 0 *
#    - AWS_S3_PATH=
#    - AWS_KEY=
#    - AWS_SECERT=
#    - DBNAME=sentry 

postgres:
  image: postgres:9.4.5
  restart: always
  environment:
    - POSTGRES_PASSWORD=sentry
    - POSTGRES_USER=sentry
  volumes:
    - /var/lib/postgresql/data

redis:
  image: redis
  restart: always

celery-beat:
  build: .
  restart: always
  links:
    - redis
    - postgres
  command: sentry celery beat

celery-worker:
  build: .
  restart: always
  links:
    - redis
    - postgres
  command: sentry celery worker
